import React from "react";
import { Link } from "react-router";

class Sidebar extends React.Component {
  render() {
    return (
      // <div className = "fixFont">
      // <div className="profile-sidebar">
      //   <div className="profile-userpic">
      //   </div>
      //   <div className="profile-usertitle">
      //     <div className="profile-usertitle-name">
      //       Welcome {this.props.user && this.props.user.displayName}

      //     </div>
      //     <div className="profile-usertitle-email">
      //     </div>
      //   </div>
      //   <div className="profile-usermenu">
      //   <ul className="nav">
      //       <li>
      //         <span>
      //           Number of reports generated this month: {this.props.stats && this.props.stats.totalUserTests}
      //         </span>
      //       </li>
      //       <li>
      //         <span>
      //           Total number of reports generated by clinicians: {this.props.stats && this.props.stats.totalTests}
      //         </span>
      //       </li>
      //     </ul>
      //   </div>
      //   <div className="profile-usermenu">
      //     <ul className="nav">
      //       <li>
      //         <Link activeClassName="active" to="/profile">
      //         <i className="glyphicon glyphicon-user"></i>
      //         My Profile </Link>
      //       </li>
      //       <li>
      //         <Link activeClassName="active" to="/createform">
      //         <i className="glyphicon glyphicon-plus"></i>
      //         Create a report </Link>
      //       </li>
      //       <li>
      //         <Link activeClassName="active" to="/dashboard">
      //         <i className="glyphicon glyphicon-hourglass"></i>
      //         Pending reports </Link>
      //       </li>
      //       <li>
      //         <Link activeClassName="active" to="/viewrecords">
      //         <i className="glyphicon glyphicon-ok"></i>
      //         View completed reports </Link>
      //       </li>
      //       <li>
      //         <Link activeClassName="active" to="/settings">
      //         <i className="glyphicon glyphicon-cog"></i>
      //         Settings </Link>
      //       </li>
      //     </ul>
      //   </div>
      //   </div>
      //   </div>
      <div id="sidebar" className="sidebar" data-color="black">
        <div className="sidebar-background" />
        <div className="logo">
          <img src="/images/aopaLOGO.png" alt="Logo" />
        </div>
        <div className="sidebar-wrapper">
          <ul className="nav">
            <li className="active">
              <Link activeClassName="active" className="nav-link" to="/profile">
                <i className="pe-7s-user" />
                <p>My Profile</p>
              </Link>
            </li>
            <li className>
              <Link
                activeClassName="active"
                className="nav-link"
                to="/dashboard"
              >
                <i className="pe-7s-note2" />
                <p>Pending Reports</p>
              </Link>
            </li>
            <li className>
              <Link
                activeClassName="active"
                className="nav-link"
                to="/viewrecords"
              >
                <i className="pe-7s-news-paper" />
                <p>Completed Reports</p>
              </Link>
            </li>
            <li className>
              <Link
                activeClassName="active"
                className="nav-link"
                to="/settings"
              >
                <i className="pe-7s-science" />
                <p>Settings</p>
              </Link>
            </li>
            <li className />
            <li className>
              <Link
                activeClassName="active"
                className="nav-link"
                to="/createform"
              >
                <i className="glyphicon glyphicon-plus text-muted" />
                <p>Create a New Report</p>
              </Link>
            </li>
          </ul>
        </div>
      </div>
    );
  }
}

export default Sidebar;
